apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xnmx8neiy-python 
  janus-idp.io/tekton: xnmx8neiy-python
  backstage.io/kubernetes-id: xnmx8neiy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xnmx8neiy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml