apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xnmx8neiy-python-gitops
  description: This is GitOps manifest for xnmx8neiy-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xnmx8neiy-python
    backstage.io/kubernetes-id: xnmx8neiy-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xnmx8neiy-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xnmx8neiy-python
